In [1]:
import pandas as pd

In [2]:
#reading file with genres
columns = ["wikipedia id", "freebase id", "movie name", "year released", "revenue", "runtime", "language", "country released", "genres"]
metadata = pd.read_csv("../../Downloads/MovieSummaries/movie.metadata.tsv", sep = "\t", header=None, names = columns)

metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama""}"
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","{""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0..."
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06nbt"": ""Satire"", ""/m/01z4y"": ""Comedy""}"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","{""/m/06n90"": ""Science Fiction"", ""/m/0gw5n2f"": ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","{""/m/01jfsb"": ""Thriller"", ""/m/03npn"": ""Horror""..."

In [3]:
pwd

'/Users/cailley/Downloads/NLP-final-project'

In [4]:
import json
#genres column is in json format, so load column as dictionary
metadata.genres = metadata.genres.apply(json.loads)

In [5]:
#get only genres in each dictionary for each row
metadata.genres = metadata.genres.apply(lambda x : list(x.values()))

In [6]:
metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Thriller, Science Fiction, Horror, Adventure,..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Mystery, Biographical film, Drama, Crime Drama]"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","[Crime Fiction, Drama]"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","[Thriller, Erotic thriller, Psychological thri..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}",[Drama]
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}",[Drama]
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","[Biographical film, Drama, Documentary]"
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Satire, Comedy]"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","[Science Fiction, Japanese Movies, Adventure, ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","[Thriller, Horror, Slasher, Teen]"

In [7]:
#reading summary file
columns = ["wikipedia id", "summary"]
summ = pd.read_csv("../../Downloads/MovieSummaries/plot_summaries.txt", sep = "\t", header=None, names = columns)

summ

       wikipedia id                                            summary
0          23890098  Shlykov, a hard-working taxi driver and Lyosha...
1          31186339  The nation of Panem consists of a wealthy Capi...
2          20663735  Poovalli Induchoodan  is sentenced for six yea...
3           2231378  The Lemon Drop Kid , a New York City swindler,...
4            595909  Seventh-day Adventist Church pastor Michael Ch...
...             ...                                                ...
42298      34808485  The story is about Reema , a young Muslim scho...
42299       1096473  In 1928 Hollywood, director Leo Andreyev  look...
42300      35102018  American Luthier focuses on Randy Parsons’ tra...
42301       8628195  Abdur Rehman Khan , a middle-aged dry fruit se...
42302       6040782  1940 - Operation Dynamo has just taken place. ...

[42303 rows x 2 columns]

In [8]:
#looking at example summary
summ.iloc[1]['summary']

'The nation of Panem consists of a wealthy Capitol and twelve poorer districts. As punishment for a past rebellion, each district must provide a boy and girl  between the ages of 12 and 18 selected by lottery  for the annual Hunger Games. The tributes must fight to the death in an arena; the sole survivor is rewarded with fame and wealth. In her first Reaping, 12-year-old Primrose Everdeen is chosen from District 12. Her older sister Katniss volunteers to take her place. Peeta Mellark, a baker\'s son who once gave Katniss bread when she was starving, is the other District 12 tribute. Katniss and Peeta are taken to the Capitol, accompanied by their frequently drunk mentor, past victor Haymitch Abernathy. He warns them about the "Career" tributes who train intensively at special academies and almost always win. During a TV interview with Caesar Flickerman, Peeta unexpectedly reveals his love for Katniss. She is outraged, believing it to be a ploy to gain audience support, as "sponsors" may provide in-Games gifts of food, medicine, and tools. However, she discovers Peeta meant what he said. The televised Games begin with half of the tributes killed in the first few minutes; Katniss barely survives ignoring Haymitch\'s advice to run away from the melee over the tempting supplies and weapons strewn in front of a structure called the Cornucopia. Peeta forms an uneasy alliance with the four Careers. They later find Katniss and corner her up a tree. Rue, hiding in a nearby tree, draws her attention to a poisonous tracker jacker nest hanging from a branch. Katniss drops it on her sleeping besiegers. They all scatter, except for Glimmer, who is killed by the insects. Hallucinating due to tracker jacker venom, Katniss is warned to run away by Peeta. Rue cares for Katniss for a couple of days until she recovers. Meanwhile, the alliance has gathered all the supplies into a pile. Katniss has Rue draw them off, then destroys the stockpile by setting off the mines planted around it. Furious, Cato kills the boy assigned to guard it. As Katniss runs from the scene, she hears Rue calling her name. She finds Rue trapped and releases her. Marvel, a tribute from District 1, throws a spear at Katniss, but she dodges the spear, causing it to stab Rue in the stomach instead. Katniss shoots him dead with an arrow. She then comforts the dying Rue with a song. Afterward, she gathers and arranges flowers around Rue\'s body. When this is televised, it sparks a riot in Rue\'s District 11. President Snow summons Seneca Crane, the Gamemaker, to express his displeasure at the way the Games are turning out. Since Katniss and Peeta have been presented to the public as "star-crossed lovers", Haymitch is able to convince Crane to make a rule change to avoid inciting further riots. It is announced that tributes from the same district can win as a pair. Upon hearing this, Katniss searches for Peeta and finds him with an infected sword wound in the leg. She portrays herself as deeply in love with him and gains a sponsor\'s gift of soup. An announcer proclaims a feast, where the thing each survivor needs most will be provided. Peeta begs her not to risk getting him medicine. Katniss promises not to go, but after he falls asleep, she heads to the feast. Clove ambushes her and pins her down. As Clove gloats, Thresh, the other District 11 tribute, kills Clove after overhearing her tormenting Katniss about killing Rue. He spares Katniss "just this time...for Rue". The medicine works, keeping Peeta mobile. Foxface, the girl from District 5, dies from eating nightlock berries she stole from Peeta; neither knew they are highly poisonous. Crane changes the time of day in the arena to late at night and unleashes a pack of hound-like creatures to speed things up. They kill Thresh and force Katniss and Peeta to flee to the roof of the Cornucopia, where they encounter Cato. After a battle, Katniss wounds Cato with an arrow and Peeta hurls him to the creatures below. Katniss shoots Cato to spare him a prolonged death. With Peeta and Katniss apparently victorious, the rule change allowing two winners is suddenly revoked. Peeta tells Katniss to shoot him. Instead, she gives him half of the nightlock. However, before they can commit suicide, they are hastily proclaimed the victors of the 74th Hunger Games. Haymitch warns Katniss that she has made powerful enemies after her display of defiance. She and Peeta return to District 12, while Crane is locked in a room with a bowl of nightlock berries, and President Snow considers the situation.'

In [9]:
#drop unneeded columns
meta = metadata.drop(["freebase id", "year released", "revenue", "runtime", "country released"], axis=1)

#merge dataframes with genres and summaries 
df = pd.merge(meta, summ, how="inner", on="wikipedia id")

df_3 = df.copy()
df

,wikipedia id,movie name,language,genres,summary
0,975900,Ghosts of Mars,"{""/m/02h40lc"": ""English Language""}","[Thriller, Science Fiction, Horror, Adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,"{""/m/02h40lc"": ""English Language""}","[Thriller, Erotic thriller, Psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,"{""/m/04306rv"": ""German Language""}",[Drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"{""/m/02h40lc"": ""English Language""}","[Family Film, Fantasy, Adventure, World cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"{""/m/02h40lc"": ""English Language""}","[Romantic comedy, Ensemble Film, Comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...,...
42199,23851782,The Ghost Train,"{""/m/02h40lc"": ""English Language""}","[Crime Fiction, Thriller, Comedy, Supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,"{""/m/02h40lc"": ""English Language""}",[Drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"{""/m/02h40lc"": ""English Language""}","[Biographical film, Drama, Documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"{""/m/03_9r"": ""Japanese Language""}","[Science Fiction, Japanese Movies, Adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"{""/m/02h40lc"": ""English Language""}","[Thriller, Horror, Slasher, Teen]",The movie is about a teenage girl who loves ho...

In [10]:
df.language = df.language.apply(json.loads)
df.language = df.language.apply(lambda x : list(x.values()))

df

,wikipedia id,movie name,language,genres,summary
0,975900,Ghosts of Mars,[English Language],"[Thriller, Science Fiction, Horror, Adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,[English Language],"[Thriller, Erotic thriller, Psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,[German Language],[Drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,[English Language],"[Family Film, Fantasy, Adventure, World cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,[English Language],"[Romantic comedy, Ensemble Film, Comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...,...
42199,23851782,The Ghost Train,[English Language],"[Crime Fiction, Thriller, Comedy, Supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[English Language],[Drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,[English Language],"[Biographical film, Drama, Documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,[Japanese Language],"[Science Fiction, Japanese Movies, Adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,[English Language],"[Thriller, Horror, Slasher, Teen]",The movie is about a teenage girl who loves ho...

In [11]:
df.language.value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[English Language]                                                                         20548
[]                                                                                          5264
[Hindi Language]                                                                            1692
[Tamil Language]                                                                             970
[French Language]                                                                            893
                                                                                           ...
[Chinese language, Japanese Language, Russian Language]                                        1
[Banyumasan language, Indonesian Language]                                                     1
[Mandarin Chinese, Portuguese Language, Standard Mandarin, English Language, Cantonese]        1
[Persian Language, Italian Language, English Language, Pashto language]                        1
[Italian Language, English Language, Norwegian Language]                                       1
Name: language, Length: 1449, dtype: int64

In [28]:
from collections import Counter 

genre_counter = Counter()

df.genres.apply(genre_counter.update)

#genre_counter

0        None
1        None
2        None
3        None
4        None
         ...
42199    None
42200    None
42201    None
42202    None
42203    None
Name: genres, Length: 42204, dtype: object

In [13]:
genre_counter.most_common(35)

[('Drama', 19134),
 ('Comedy', 10467),
 ('Romance Film', 6666),
 ('Thriller', 6530),
 ('Action', 5868),
 ('World cinema', 5153),
 ('Crime Fiction', 4275),
 ('Horror', 4082),
 ('Black-and-white', 3731),
 ('Indie', 3668),
 ('Action/Adventure', 3553),
 ('Adventure', 3248),
 ('Family Film', 3219),
 ('Short Film', 3192),
 ('Romantic drama', 2572),
 ('Animation', 2441),
 ('Musical', 2414),
 ('Science Fiction', 2339),
 ('Mystery', 2119),
 ('Romantic comedy', 2075),
 ('Fantasy', 2012),
 ('Comedy film', 1778),
 ('Crime Thriller', 1682),
 ('War film', 1556),
 ('Period piece', 1321),
 ('Japanese Movies', 1290),
 ('Comedy-drama', 1261),
 ('Film adaptation', 1225),
 ('Documentary', 1213),
 ('Silent film', 1199),
 ('Psychological thriller', 1138),
 ('Bollywood', 1058),
 ('Western', 1022),
 ('Chinese Movies', 998),
 ('Black comedy', 834)]

In [14]:
target = ['Drama', 'Comedy', 'Romance', 'Thriller', 'Action', 'World cinema', 'Crime', 'Horror', 'Adventure'
         'Family film', 'Short film', 'Musical', 'Science Fiction', 'Mystery', 'Fantasy', 'Documentary', 'Silent Film']

len(target)

16

In [15]:
import re 

def change_genre(r, genres, target_genre): 
    return [target_genre if re.search(r, genre) else genre for genre in genres]

In [16]:
df_2 = df.copy()

In [17]:
romance_re = r'Roman'
action_re = r'Action'

In [27]:
count = Counter()

df_2.genres.apply(count.update)

#count.most_common()

0        None
1        None
2        None
3        None
4        None
         ...
42199    None
42200    None
42201    None
42202    None
42203    None
Name: genres, Length: 42204, dtype: object

In [19]:
# empty genres list
df_2.genres.astype(bool).value_counts()

True     41793
False      411
Name: genres, dtype: int64

In [20]:
#df_2.genres = df_2.genres.apply(lambda l: change_genre(romance_re, l, 'Romance'))

#def change_genre(r, genres, target_genre): 
#    return [target_genre if re.search(r, genre) else genre for genre in genres]

                                
def genre_lower(genre_l):
    for i in range(len(genre_l)):
        genre_l[i] = genre_l[i].lower()
    return genre_l
        
df_3.genres = df_3.genres.apply(lambda l: genre_lower(l))
        
df_3.genres[1]

['thriller', 'erotic thriller', 'psychological thriller']

In [21]:
import re
reee = re.compile("thriller")
list(filter(reee.match, df_3.genres[1]))
df_3.genres[1]

l = []
l.append(df_3.genres[1][0])
l

['thriller']

In [22]:
import re

regex_list = ["drama", "comedy", "action", "adventure", "roman", "crime", "thriller", "family", "world cinema", "horror", "short film", "science fiction", "mystery", "fantasy", "documentary", "silent film"]
for i in range(len(df_3.genres)):     #genre in df_3.genres:
    new_gen_l = []
    for regex in regex_list:
        r = re.compile(regex)
        found = list(filter(r.match, df_3.genres[i]))
        if found:
            new_gen_l.append(regex)
    df_3.genres[i] = new_gen_l
    #print(new_gen_l)
            
        
df_3.genres[1]

/var/folders/hj/0nc8czp51fq_dklf2zvlk5jm0000gq/T/ipykernel_47914/3641997716.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3.genres[i] = new_gen_l

['thriller']

In [25]:
df_3.genres

0        [action, adventure, thriller, horror, science ...
1                                               [thriller]
2                                                  [drama]
3               [adventure, family, world cinema, fantasy]
4                                   [drama, comedy, roman]
                               ...
42199                            [comedy, crime, thriller]
42200                                              [drama]
42201                                 [drama, documentary]
42202      [drama, adventure, short film, science fiction]
42203                                   [thriller, horror]
Name: genres, Length: 42204, dtype: object

In [29]:
from collections import Counter 

genre_3c = Counter()

df_3.genres.apply(genre_3c.update)

genre_3c.most_common()

[('drama', 19134),
 ('comedy', 12494),
 ('roman', 7254),
 ('action', 6806),
 ('thriller', 6530),
 ('world cinema', 5153),
 ('crime', 5133),
 ('horror', 4092),
 ('family', 3771),
 ('adventure', 3290),
 ('short film', 3192),
 ('science fiction', 2342),
 ('mystery', 2119),
 ('fantasy', 2102),
 ('documentary', 1213),
 ('silent film', 1199)]

In [31]:
df3gencs = []
for genre in df_3.genres:
    c = 0
    for el in genre:
        c += 1
    df3gencs.append(c)

#df3gencs

In [33]:
df3countsCounter = Counter(df3gencs)
df3countsCounter.most_common()

[(1, 13819),
 (2, 12793),
 (3, 8449),
 (4, 3512),
 (0, 2297),
 (5, 1034),
 (6, 254),
 (7, 39),
 (8, 6),
 (9, 1)]

In [35]:
pwd

'/Users/cailley/Downloads/NLP-final-project'