<a href="https://colab.research.google.com/github/CIT-NLP/NLP-final-project/blob/main/366_final_project_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Downloading the Dataset

In [1]:
!gdown https://drive.google.com/u/0/uc?id=1v9u3NTeJtlIYdNGLqMa2kZNTGjMCvjjh

Downloading...
From: https://drive.google.com/u/0/uc?id=1v9u3NTeJtlIYdNGLqMa2kZNTGjMCvjjh
To: /content/MovieSummaries.tar
100% 134M/134M [00:00<00:00, 206MB/s]

In [ ]:
!ls

MovieSummaries.tar  sample_data

In [ ]:
!tar -xf MovieSummaries.tar && ls

MovieSummaries	MovieSummaries.tar  sample_data

# Loading and Cleaning

In [ ]:
import pandas as pd

In [ ]:
#reading file with genres
columns = ["wikipedia id", "freebase id", "movie name", "year released", "revenue", "runtime", "language", "country released", "genres"]
metadata = pd.read_csv("./MovieSummaries/movie.metadata.tsv", sep = "\t", header=None, names = columns)

metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenÃ©t Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama""}"
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","{""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0..."
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06nbt"": ""Satire"", ""/m/01z4y"": ""Comedy""}"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","{""/m/06n90"": ""Science Fiction"", ""/m/0gw5n2f"": ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","{""/m/01jfsb"": ""Thriller"", ""/m/03npn"": ""Horror""..."

In [ ]:
import json
#genres column is in json format, so load column as dictionary
metadata.genres = metadata.genres.apply(json.loads)

#get only genres in each dictionary for each row
metadata.genres = metadata.genres.apply(lambda x : list(x.values()))

metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Thriller, Science Fiction, Horror, Adventure,..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenÃ©t Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Mystery, Biographical film, Drama, Crime Drama]"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","[Crime Fiction, Drama]"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","[Thriller, Erotic thriller, Psychological thri..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}",[Drama]
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}",[Drama]
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","[Biographical film, Drama, Documentary]"
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Satire, Comedy]"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","[Science Fiction, Japanese Movies, Adventure, ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","[Thriller, Horror, Slasher, Teen]"

In [ ]:
#reading summary file
columns = ["wikipedia id", "summary"]
summ = pd.read_csv("./MovieSummaries/plot_summaries.txt", sep = "\t", header=None, names = columns)

summ

       wikipedia id                                            summary
0          23890098  Shlykov, a hard-working taxi driver and Lyosha...
1          31186339  The nation of Panem consists of a wealthy Capi...
2          20663735  Poovalli Induchoodan  is sentenced for six yea...
3           2231378  The Lemon Drop Kid , a New York City swindler,...
4            595909  Seventh-day Adventist Church pastor Michael Ch...
...             ...                                                ...
42298      34808485  The story is about Reema , a young Muslim scho...
42299       1096473  In 1928 Hollywood, director Leo Andreyev  look...
42300      35102018  American Luthier focuses on Randy Parsonsâ tra...
42301       8628195  Abdur Rehman Khan , a middle-aged dry fruit se...
42302       6040782  1940 - Operation Dynamo has just taken place. ...

[42303 rows x 2 columns]

In [ ]:
#drop unneeded columns
meta = metadata.drop(["freebase id", "year released", "revenue", "runtime", "country released", 'language'], axis=1)

#merge dataframes with genres and summaries 
df = pd.merge(meta, summ, how="inner", on="wikipedia id")

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[Thriller, Science Fiction, Horror, Adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,"[Thriller, Erotic thriller, Psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,[Drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"[Family Film, Fantasy, Adventure, World cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[Romantic comedy, Ensemble Film, Comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...
42199,23851782,The Ghost Train,"[Crime Fiction, Thriller, Comedy, Supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[Drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"[Biographical film, Drama, Documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[Science Fiction, Japanese Movies, Adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[Thriller, Horror, Slasher, Teen]",The movie is about a teenage girl who loves ho...

In [ ]:
from collections import Counter 

genre_counter = Counter()

df.genres.apply(genre_counter.update)

genre_counter

Counter({'Absurdism': 79,
         'Acid western': 7,
         'Action': 5868,
         'Action Comedy': 142,
         'Action Thrillers': 405,
         'Action/Adventure': 3553,
         'Addiction Drama': 42,
         'Adult': 117,
         'Adventure': 3248,
         'Adventure Comedy': 123,
         'Airplanes and airports': 53,
         'Albino bias': 14,
         'Alien Film': 97,
         'Alien invasion': 4,
         'Americana': 91,
         'Animal Picture': 141,
         'Animals': 15,
         'Animated Musical': 43,
         'Animated cartoon': 94,
         'Animation': 2441,
         'Anime': 305,
         'Anthology': 7,
         'Anthropology': 2,
         'Anti-war': 32,
         'Anti-war film': 31,
         'Apocalyptic and post-apocalyptic fiction': 32,
         'Archaeology': 10,
         'Archives and records': 6,
         'Art film': 351,
         'Auto racing': 50,
         'Avant-garde': 83,
         'B-Western': 19,
         'B-movie': 386,
         'Backstage Musical': 20,
         'Baseball': 9,
         'Beach Film': 19,
         'Beach Party film': 2,
         'Bengali Cinema': 10,
         'Biker Film': 20,
         'Biographical film': 625,
         'Biography': 592,
         'Biopic [feature]': 365,
         'Black comedy': 834,
         'Black-and-white': 3731,
         'Blaxploitation': 79,
         'Bloopers & Candid Camera': 3,
         'Bollywood': 1058,
         'Boxing': 51,
         'Breakdance': 1,
         'British Empire Film': 20,
         'British New Wave': 13,
         'Bruceploitation': 3,
         'Buddy Picture': 1,
         'Buddy cop': 11,
         'Buddy film': 325,
         'Business': 4,
         'C-Movie': 1,
         'Camp': 3,
         'Caper story': 80,
         'Cavalry Film': 12,
         'Chase Movie': 100,
         'Chick flick': 1,
         'Childhood Drama': 111,
         "Children's": 412,
         "Children's Entertainment": 11,
         "Children's Fantasy": 244,
         "Children's Issues": 1,
         "Children's/Family": 759,
         'Chinese Movies': 998,
         'Christian film': 116,
         'Christmas movie': 80,
         'Clay animation': 4,
         'Cold War': 10,
         'Combat Films': 84,
         'Comdedy': 1,
         'Comedy': 10467,
         'Comedy Thriller': 78,
         'Comedy Western': 53,
         'Comedy film': 1778,
         'Comedy horror': 19,
         'Comedy of Errors': 169,
         'Comedy of manners': 212,
         'Comedy-drama': 1261,
         'Coming of age': 741,
         'Coming-of-age film': 4,
         'Computer Animation': 195,
         'Computers': 4,
         'Concert film': 11,
         'Conspiracy fiction': 2,
         'Costume Adventure': 77,
         'Costume Horror': 55,
         'Costume drama': 367,
         'Courtroom Comedy': 6,
         'Courtroom Drama': 184,
         'Creature Film': 347,
         'Crime': 26,
         'Crime Comedy': 231,
         'Crime Drama': 391,
         'Crime Fiction': 4275,
         'Crime Thriller': 1682,
         'Cult': 680,
         'Culture & Society': 204,
         'Cyberpunk': 5,
         'Czechoslovak New Wave': 7,
         'Dance': 69,
         'Demonic child': 6,
         'Detective': 282,
         'Detective fiction': 225,
         'Disaster': 238,
         'Docudrama': 252,
         'Documentary': 1213,
         'Dogme 95': 17,
         'Domestic Comedy': 172,
         'Doomsday film': 112,
         'Drama': 19134,
         'Dystopia': 84,
         'Ealing Comedies': 12,
         'Early Black Cinema': 6,
         'Education': 3,
         'Educational': 16,
         'Ensemble Film': 349,
         'Environmental Science': 6,
         'Epic': 196,
         'Epic Western': 17,
         'Erotic Drama': 112,
         'Erotic thriller': 170,
         'Erotica': 235,
         'Escape Film': 45,
         'Essay Film': 8,
         'Existentialism': 34,
         'Experimental film': 107,
         'Exploitation': 12,
         'Expressionism': 2,
         'Extreme Sports': 10,
         'Fairy tale': 48,
         'Family & Personal Relationships': 10,
         'Family Drama': 766,
         'Family Film': 3219,
         'Family-Oriented Adventure': 213,
         'Fan film': 18,
         'Fantasy': 2012,
         'Fantasy Adventure': 190,
         'Fantasy Comedy': 196,
         'Fantasy Drama': 16,
         'Feature film': 8,
         'Female buddy film': 4,
         'Feminist Film': 76,
         'Fictional film': 8,
         'Filipino': 10,
         'Filipino Movies': 220,
         'Film': 19,
         'Film & Television History': 11,
         'Film adaptation': 1225,
         'Film noir': 524,
         'Film Ã  clef': 29,
         'Film-Opera': 3,
         'Filmed Play': 3,
         'Finance & Investing': 4,
         'Foreign legion': 10,
         'Future noir': 29,
         'Gangster Film': 338,
         'Gay': 219,
         'Gay Interest': 217,
         'Gay Themed': 264,
         'Gay pornography': 21,
         'Gender Issues': 19,
         'Giallo': 25,
         'Glamorized Spy Film': 45,
         'Goat gland': 4,
         'Gothic Film': 62,
         'Graphic & Applied Arts': 4,
         'Gross out': 58,
         'Gross-out film': 58,
         'Gulf War': 5,
         'Hagiography': 19,
         'Hardcore pornography': 7,
         'Haunted House Film': 65,
         'Health & Fitness': 3,
         'Heaven-Can-Wait Fantasies': 21,
         'Heavenly Comedy': 27,
         'Heist': 145,
         'Hip hop movies': 31,
         'Historical Documentaries': 2,
         'Historical Epic': 63,
         'Historical drama': 107,
         'Historical fiction': 305,
         'History': 358,
         'Holiday Film': 94,
         'Homoeroticism': 1,
         'Horror': 4082,
         'Horror Comedy': 206,
         'Horse racing': 8,
         'Humour': 4,
         'Hybrid Western': 29,
         'Illnesses & Disabilities': 14,
         'Indian Western': 18,
         'Indie': 3668,
         'Inspirational Drama': 27,
         'Instrumental Music': 4,
         'Interpersonal Relationships': 21,
         'Inventions & Innovations': 4,
         'Japanese Movies': 1290,
         'Journalism': 2,
         'Jukebox musical': 7,
         'Jungle Film': 62,
         'Juvenile Delinquency Film': 42,
         'Kafkaesque': 6,
         'Kitchen sink realism': 14,
         'LGBT': 825,
         'Language & Literature': 8,
         'Latino': 3,
         'Law & Crime': 21,
         'Legal drama': 8,
         'Libraries and librarians': 5,
         'Linguistics': 1,
         'Live action': 2,
         'Malayalam Cinema': 12,
         'Marriage Drama': 137,
         'Martial Arts Film': 706,
         'Master Criminal Films': 25,
         'Media Satire': 71,
         'Media Studies': 7,
         'Medical fiction': 56,
         'Melodrama': 499,
         'Mockumentary': 97,
         'Mondo film': 5,
         'Monster': 113,
         'Monster movie': 168,
         'Movie serial': 11,
         'Movies About Gladiators': 5,
         'Mumblecore': 7,
         'Music': 356,
         'Musical': 2414,
         'Musical Drama': 136,
         'Musical comedy': 175,
         'Mystery': 2119,
         'Mythological Fantasy': 26,
         'Natural disaster': 14,
         'Natural horror films': 153,
         'Nature': 17,
         'Neo-noir': 57,
         'Neorealism': 1,
         'New Hollywood': 86,
         'New Queer Cinema': 1,
         'News': 7,
         'Ninja movie': 1,
         'Northern': 7,
         'Nuclear warfare': 3,
         'Operetta': 4,
         'Outlaw': 5,
         'Outlaw biker film': 12,
         'Parkour in popular culture': 6,
         'Parody': 767,
         'Patriotic film': 1,
         'Period Horror': 2,
         'Period piece': 1321,
         'Pinku eiga': 24,
         'Plague': 4,
         'Point of view shot': 3,
         'Political Documetary': 1,
         'Political cinema': 176,
         'Political drama': 531,
         'Political satire': 78,
         'Political thriller': 195,
         'Pornographic movie': 145,
         'Pornography': 7,
         'Pre-Code': 130,
         'Prison': 90,
         'Prison escape': 2,
         'Prison film': 12,
         'Private military company': 2,
         'Propaganda film': 77,
         'Psycho-biddy': 10,
         'Psychological horror': 3,
         'Psychological thriller': 1138,
         'Punk rock': 23,
         'Race movie': 3,
         'Reboot': 8,
         'Religious Film': 61,
         'Remake': 85,
         'Revenge': 2,
         'Revisionist Fairy Tale': 2,
         'Revisionist Western': 60,
         'Road movie': 268,
         'Road-Horror': 19,
         'Roadshow theatrical release': 32,
         'Roadshow/Carny': 4,
         'Rockumentary': 40,
         'Romance Film': 6666,
         'Romantic comedy': 2075,
         'Romantic drama': 2572,
         'Romantic fantasy': 59,
         'Romantic thriller': 1,
         'Samurai cinema': 27,
         'Satire': 532,
         'School story': 4,
         'Sci Fi Pictures original films': 4,
         'Sci-Fi Adventure': 32,
         'Sci-Fi Horror': 124,
         'Sci-Fi Thriller': 5,
         'Science Fiction': 2339,
         'Science fiction Western': 5,
         'Screwball comedy': 246,
         'Sex comedy': 253,
         'Sexploitation': 82,
         'Short Film': 3192,
         'Silent film': 1199,
         'Silhouette animation': 1,
         'Singing cowboy': 3,
         'Slapstick': 518,
         'Slasher': 654,
         'Slice of life story': 94,
         'Social issues': 101,
         'Social problem film': 92,
         'Softcore Porn': 41,
         'Space opera': 5,
         'Space western': 12,
         'Spaghetti Western': 56,
         'Splatter film': 28,
         'Sponsored film': 4,
         'Sports': 672,
         'Spy': 342,
         'Stand-up comedy': 12,
         'Star vehicle': 2,
         'Statutory rape': 1,
         'Steampunk': 30,
         'Stoner film': 46,
         'Stop motion': 134,
         'Superhero': 111,
         'Superhero movie': 258,
         'Supermarionation': 3,
         'Supernatural': 571,
         'Surrealism': 99,
         'Suspense': 651,
         'Swashbuckler films': 104,
         'Sword and Sandal': 16,
         'Sword and sorcery': 39,
         'Sword and sorcery films': 37,
         'Tamil cinema': 63,
         'Teen': 824,
         'Television movie': 665,
         'The Netherlands in World War II': 2,
         'Therimin music': 4,
         'Thriller': 6530,
         'Time travel': 77,
         'Tokusatsu': 2,
         'Tollywood': 32,
         'Tragedy': 79,
         'Tragicomedy': 51,
         'Travel': 14,
         'Vampire movies': 3,
         'War effort': 1,
         'War film': 1556,
         'Werewolf fiction': 4,
         'Western': 1022,
         'Whodunit': 43,
         'Women in prison films': 13,
         'Workplace Comedy': 84,
         'World History': 10,
         'World cinema': 5153,
         'Wuxia': 79,
         'Z movie': 2,
         'Zombie Film': 234})

In [ ]:
genre_counter.most_common(35)

[('Drama', 19134),
 ('Comedy', 10467),
 ('Romance Film', 6666),
 ('Thriller', 6530),
 ('Action', 5868),
 ('World cinema', 5153),
 ('Crime Fiction', 4275),
 ('Horror', 4082),
 ('Black-and-white', 3731),
 ('Indie', 3668),
 ('Action/Adventure', 3553),
 ('Adventure', 3248),
 ('Family Film', 3219),
 ('Short Film', 3192),
 ('Romantic drama', 2572),
 ('Animation', 2441),
 ('Musical', 2414),
 ('Science Fiction', 2339),
 ('Mystery', 2119),
 ('Romantic comedy', 2075),
 ('Fantasy', 2012),
 ('Comedy film', 1778),
 ('Crime Thriller', 1682),
 ('War film', 1556),
 ('Period piece', 1321),
 ('Japanese Movies', 1290),
 ('Comedy-drama', 1261),
 ('Film adaptation', 1225),
 ('Documentary', 1213),
 ('Silent film', 1199),
 ('Psychological thriller', 1138),
 ('Bollywood', 1058),
 ('Western', 1022),
 ('Chinese Movies', 998),
 ('Black comedy', 834)]

In [ ]:
#lowercase genres 
def genre_lower(genre_l):
    for i in range(len(genre_l)):
        genre_l[i] = genre_l[i].lower()
    return genre_l

df.genres = df.genres.apply(genre_lower)

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[thriller, science fiction, horror, adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,"[thriller, erotic thriller, psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,[drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"[family film, fantasy, adventure, world cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[romantic comedy, ensemble film, comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...
42199,23851782,The Ghost Train,"[crime fiction, thriller, comedy, supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"[biographical film, drama, documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[science fiction, japanese movies, adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[thriller, horror, slasher, teen]",The movie is about a teenage girl who loves ho...

In [ ]:
import re

regex_list = ['drama', 'comedy', 'action', 'adventure', 'roman', 'crime',
              'thriller', 'family', 'world cinema', 'horror',
              'short film', 'science fiction', 'mystery', 
              'fantasy', 'documentary', 'silent film']

compiled_regex = [re.compile(regex) for regex in regex_list]


def collapse_genres(genres, regex_list, compiled_regex):
  new_gen_l = []

  for i, co_regex in enumerate(compiled_regex): 
    found = list(filter(co_regex.match, genres))
    if found: 
      if regex_list[i] == 'roman': 
        new_gen_l.append('romance')
      else: 
        new_gen_l.append(regex_list[i])

  return new_gen_l
   

df.genres = df.genres.apply(lambda l: collapse_genres(l, regex_list, compiled_regex))

# remove rows with empty genre lists 
df = df[df.genres.astype(bool)]

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[action, adventure, thriller, horror, science ...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,[thriller],A series of murders of rich young women throug...
2,261236,A Woman in Flames,[drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"[adventure, family, world cinema, fantasy]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[drama, comedy, romance]","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...
42199,23851782,The Ghost Train,"[comedy, crime, thriller]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"[drama, documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[drama, adventure, short film, science fiction]","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[thriller, horror]",The movie is about a teenage girl who loves ho...

In [ ]:
count = Counter()
df.genres.apply(count.update)

count.most_common()

[('drama', 19134),
 ('comedy', 12494),
 ('romance', 7254),
 ('action', 6806),
 ('thriller', 6530),
 ('world cinema', 5153),
 ('crime', 5133),
 ('horror', 4092),
 ('family', 3771),
 ('adventure', 3290),
 ('short film', 3192),
 ('science fiction', 2342),
 ('mystery', 2119),
 ('fantasy', 2102),
 ('documentary', 1213),
 ('silent film', 1199)]

In [ ]:
df3gencs = []
for genre in df.genres:
    c = 0
    for el in genre:
        c += 1
    df3gencs.append(c)

df3countsCounter = Counter(df3gencs)
df3countsCounter.most_common()

[(1, 13819),
 (2, 12793),
 (3, 8449),
 (4, 3512),
 (5, 1034),
 (6, 254),
 (7, 39),
 (8, 6),
 (9, 1)]

## Spacy Tokenizing

In [ ]:
!pip install -Uqq spacy
!python -m spacy download en_core_web_sm

     |ââââââââââââââââââââââââââââââââ| 6.0 MB 5.5 MB/s
     |ââââââââââââââââââââââââââââââââ| 457 kB 41.7 MB/s
     |ââââââââââââââââââââââââââââââââ| 181 kB 37.4 MB/s
     |ââââââââââââââââââââââââââââââââ| 10.1 MB 35.6 MB/s
     |ââââââââââââââââââââââââââââââââ| 42 kB 1.4 MB/s
     |ââââââââââââââââââââââââââââââââ| 653 kB 47.5 MB/s
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
Collecting en-core-web-sm==3.2.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl (13.9 MB)
     |ââââââââââââââââââââââââââââââââ| 13.9 MB 5.4 MB/s
Requirement already satisfied: spacy<3.3.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.2.0) (3.2.4)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.21.6)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.4.1)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.4.1)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.9.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (4.64.0)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.0.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.3.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.8 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (21.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.6)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.6)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.8.2)
Requirement already satisfied: click<8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (7.1.2)
Requirement already satisfied: thinc<8.1.0,>=8.0.12 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (8.0.15)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.0.6)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.6.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.4.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (57.4.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.23.0)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.10.0.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.11.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.8)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (5.2.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.24.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.1)
Installing collected packages: en-core-web-sm
  Attempting uninstall: en-core-web-sm
    Found existing installation: en-core-web-sm 2.2.5
    Uninstalling en-core-web-sm-2.2.5:
      Successfully uninstalled en-core-web-sm-2.2.5
Successfully installed en-core-web-sm-3.2.0
â Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
import spacy

spacy.__version__

'3.2.4'

In [ ]:
nlp = spacy.load("en_core_web_sm")

# sentence segmenter 
#nlp.enable_pipe("senter")

In [ ]:
# looking at example summary 
type(df.iloc[10]['summary'])

str

In [ ]:
def unique_tokens(summ, token_set):
  doc = nlp(summ)
  tokens = [token.text for token in doc if not token.text.isspace()]
  token_set.update(tokens)

In [ ]:
import time 

tok = set()
start = time.time()

df.summary.apply(lambda sum: unique_tokens(sum, tok))

print("Time taken : " + time.time() - start)


tok

TypeError: ignored