<a href="https://colab.research.google.com/github/CIT-NLP/NLP-final-project/blob/main/366_final_project_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Downloading the Dataset

In [1]:
!gdown https://drive.google.com/u/0/uc?id=1v9u3NTeJtlIYdNGLqMa2kZNTGjMCvjjh

Downloading...
From: https://drive.google.com/u/0/uc?id=1v9u3NTeJtlIYdNGLqMa2kZNTGjMCvjjh
To: /content/MovieSummaries.tar
100% 134M/134M [00:00<00:00, 165MB/s]

In [2]:
!ls

MovieSummaries.tar  sample_data

In [3]:
!tar -xf MovieSummaries.tar && ls

MovieSummaries	MovieSummaries.tar  sample_data

# Loading and Cleaning

In [32]:
import pandas as pd

In [41]:
#reading file with genres
columns = ["wikipedia id", "freebase id", "movie name", "year released", "revenue", "runtime", "language", "country released", "genres"]
metadata = pd.read_csv("./MovieSummaries/movie.metadata.tsv", sep = "\t", header=None, names = columns)

metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenÃ©t Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama""}"
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","{""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0..."
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06nbt"": ""Satire"", ""/m/01z4y"": ""Comedy""}"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","{""/m/06n90"": ""Science Fiction"", ""/m/0gw5n2f"": ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","{""/m/01jfsb"": ""Thriller"", ""/m/03npn"": ""Horror""..."

In [42]:
import json
#genres column is in json format, so load column as dictionary
metadata.genres = metadata.genres.apply(json.loads)

#get only genres in each dictionary for each row
metadata.genres = metadata.genres.apply(lambda x : list(x.values()))

metadata

,wikipedia id,freebase id,movie name,year released,revenue,runtime,language,country released,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Thriller, Science Fiction, Horror, Adventure,..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenÃ©t Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Mystery, Biographical film, Drama, Crime Drama]"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","[Crime Fiction, Drama]"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","[Thriller, Erotic thriller, Psychological thri..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}",[Drama]
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}",[Drama]
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","[Biographical film, Drama, Documentary]"
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","[Satire, Comedy]"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","[Science Fiction, Japanese Movies, Adventure, ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","[Thriller, Horror, Slasher, Teen]"

In [43]:
#reading summary file
columns = ["wikipedia id", "summary"]
summ = pd.read_csv("./MovieSummaries/plot_summaries.txt", sep = "\t", header=None, names = columns)

summ

       wikipedia id                                            summary
0          23890098  Shlykov, a hard-working taxi driver and Lyosha...
1          31186339  The nation of Panem consists of a wealthy Capi...
2          20663735  Poovalli Induchoodan  is sentenced for six yea...
3           2231378  The Lemon Drop Kid , a New York City swindler,...
4            595909  Seventh-day Adventist Church pastor Michael Ch...
...             ...                                                ...
42298      34808485  The story is about Reema , a young Muslim scho...
42299       1096473  In 1928 Hollywood, director Leo Andreyev  look...
42300      35102018  American Luthier focuses on Randy Parsonsâ tra...
42301       8628195  Abdur Rehman Khan , a middle-aged dry fruit se...
42302       6040782  1940 - Operation Dynamo has just taken place. ...

[42303 rows x 2 columns]

In [44]:
#drop unneeded columns
meta = metadata.drop(["freebase id", "year released", "revenue", "runtime", "country released", 'language'], axis=1)

#merge dataframes with genres and summaries 
df = pd.merge(meta, summ, how="inner", on="wikipedia id")

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[Thriller, Science Fiction, Horror, Adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,"[Thriller, Erotic thriller, Psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,[Drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"[Family Film, Fantasy, Adventure, World cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[Romantic comedy, Ensemble Film, Comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...
42199,23851782,The Ghost Train,"[Crime Fiction, Thriller, Comedy, Supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[Drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"[Biographical film, Drama, Documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[Science Fiction, Japanese Movies, Adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[Thriller, Horror, Slasher, Teen]",The movie is about a teenage girl who loves ho...

In [ ]:
from collections import Counter 

genre_counter = Counter()

df.genres.apply(genre_counter.update)

genre_counter

In [ ]:
genre_counter.most_common(35)

In [46]:
#lowercase genres 
def genre_lower(genre_l):
    for i in range(len(genre_l)):
        genre_l[i] = genre_l[i].lower()
    return genre_l

df.genres = df.genres.apply(genre_lower)

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[thriller, science fiction, horror, adventure,...","Set in the second half of the 22nd century, th..."
1,9363483,White Of The Eye,"[thriller, erotic thriller, psychological thri...",A series of murders of rich young women throug...
2,261236,A Woman in Flames,[drama],"Eva, an upper class housewife, becomes frustra..."
3,18998739,The Sorcerer's Apprentice,"[family film, fantasy, adventure, world cinema]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[romantic comedy, ensemble film, comedy-drama,...","Adam, a San Francisco-based artist who works a..."
...,...,...,...,...
42199,23851782,The Ghost Train,"[crime fiction, thriller, comedy, supernatural]",{{plot}} The film opens with a Great Western e...
42200,35228177,Mermaids: The Body Found,[drama],Two former National Oceanic Atmospheric Admini...
42201,34980460,Knuckle,"[biographical film, drama, documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[science fiction, japanese movies, adventure, ...","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[thriller, horror, slasher, teen]",The movie is about a teenage girl who loves ho...

In [49]:
import re

# targets 
regex_list = ['drama', 'comedy', 'action', 'adventure', 'roman', 'crime',
              'thriller', 'family', 'world cinema', 'horror',
              'short film', 'science fiction', 'mystery', 
              'fantasy', 'documentary', 'silent film']

# compiled regex
compiled_regex = [re.compile(regex) for regex in regex_list]


# collapse genres to only include those in targets
def collapse_genres(genres, regex_list, compiled_regex):
  new_gen_l = []

  for i, co_regex in enumerate(compiled_regex): 
    found = list(filter(co_regex.match, genres))
    if found: 
      if regex_list[i] == 'roman': 
        new_gen_l.append('romance')
      else: 
        new_gen_l.append(regex_list[i])

  return new_gen_l
   

df.genres = df.genres.apply(lambda l: collapse_genres(l, regex_list, compiled_regex))

# remove rows with empty genre lists 
df = df[df.genres.astype(bool)]


# remove rows with only one genre listed
df = df[df.genres.map(len) > 1]

df

,wikipedia id,movie name,genres,summary
0,975900,Ghosts of Mars,"[action, adventure, thriller, horror, science ...","Set in the second half of the 22nd century, th..."
3,18998739,The Sorcerer's Apprentice,"[adventure, family, world cinema, fantasy]","Every hundred years, the evil Morgana returns..."
4,6631279,Little city,"[drama, comedy, romance]","Adam, a San Francisco-based artist who works a..."
7,11250635,The Mechanical Monsters,"[action, adventure, family, short film, scienc...",The story starts as one of the robots flies i...
8,77856,Mary Poppins,"[drama, comedy, family, fantasy]",The film opens with Mary Poppins perched in a...
...,...,...,...,...
42198,26482675,EÅrefpaÅalÄ±lar,"[drama, comedy]","The film is about two friends, Tayyar , a mafi..."
42199,23851782,The Ghost Train,"[comedy, crime, thriller]",{{plot}} The film opens with a Great Western e...
42201,34980460,Knuckle,"[drama, documentary]",{{No plot}} This film follows 12 years in the ...
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[drama, adventure, short film, science fiction]","The story takes place in the year 2092,The Sup..."
42203,12476867,Spliced,"[thriller, horror]",The movie is about a teenage girl who loves ho...

In [50]:
# genre counts following cleaning 
count = Counter()
df.genres.apply(count.update)

count.most_common()

[('drama', 14211),
 ('comedy', 9773),
 ('romance', 6678),
 ('thriller', 6166),
 ('action', 6035),
 ('world cinema', 5031),
 ('crime', 4997),
 ('family', 3554),
 ('adventure', 3096),
 ('horror', 2778),
 ('short film', 2270),
 ('science fiction', 2148),
 ('mystery', 2060),
 ('fantasy', 1996),
 ('silent film', 810),
 ('documentary', 402)]

In [51]:
# genre stats
df3gencs = []
for genre in df.genres:
    c = 0
    for el in genre:
        c += 1
    df3gencs.append(c)

df3countsCounter = Counter(df3gencs)
df3countsCounter.most_common()

[(2, 12793),
 (3, 8449),
 (4, 3512),
 (5, 1034),
 (6, 254),
 (7, 39),
 (8, 6),
 (9, 1)]





## Text Preparation

In [15]:
!pip install -Uqq spacy
!python -m spacy download en_core_web_sm

     |ââââââââââââââââââââââââââââââââ| 6.0 MB 5.5 MB/s
     |ââââââââââââââââââââââââââââââââ| 653 kB 57.1 MB/s
     |ââââââââââââââââââââââââââââââââ| 457 kB 30.6 MB/s
     |ââââââââââââââââââââââââââââââââ| 181 kB 78.5 MB/s
     |ââââââââââââââââââââââââââââââââ| 10.1 MB 50.9 MB/s
     |ââââââââââââââââââââââââââââââââ| 42 kB 1.8 MB/s
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
Collecting en-core-web-sm==3.2.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl (13.9 MB)
     |ââââââââââââââââââââââââââââââââ| 13.9 MB 5.1 MB/s
Requirement already satisfied: spacy<3.3.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.2.0) (3.2.4)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.23.0)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.10.0.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.11.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.6)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.21.6)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.4.3)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.4.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (4.64.0)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.6.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (57.4.0)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.9.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.0.6)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (0.4.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (21.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.8.2)
Requirement already satisfied: thinc<8.1.0,>=8.0.12 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (8.0.15)
Requirement already satisfied: click<8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (7.1.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.8 in /usr/local/lib/python3.7/dist-packages (from spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.8)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (5.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (3.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.3.0,>=3.2.0->en-core-web-sm==3.2.0) (2.0.1)
Installing collected packages: en-core-web-sm
  Attempting uninstall: en-core-web-sm
    Found existing installation: en-core-web-sm 2.2.5
    Uninstalling en-core-web-sm-2.2.5:
      Successfully uninstalled en-core-web-sm-2.2.5
Successfully installed en-core-web-sm-3.2.0
â Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [16]:
# restart runtime if not 3.2.4
import spacy

spacy.__version__

'3.2.4'

In [88]:
# nlp = spacy.blank('en')
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

# sentence segmenter 
#nlp.enable_pipe("senter")

nlp.pipe_names

['tok2vec', 'tagger', 'attribute_ruler', 'lemmatizer']

In [18]:
# looking at example summary 
df.iloc[10]['summary']

"The film opens with a simpleton from a small village in Tamil Nadu wanting to become a musician in the Tamil film industry. The role played by debutant Prabhu  goes to Chennai in search of his dream career where he meets Pandya . Pandya helps Prabhu into the big city life and they become good friends. Prabhu meets Yazhini  who helps him meet a famous Director, who gives Prabhu a chance to prove his music skills. On becoming a successful man, Prabhu finds love in Yazhini who helped him achieve his dream. When Prabhu decides to reveal his feelings for Yazhini, she breaks the news about Karuppu  who helped her many years ago when she was abandoned as a child during the war and also helped her reach India. Yazhini requests Prabhu to go find and talk to Karuppu about her love for Karuppu. Prabhu hides his love and sets off to find Karuppu. On meeting Karuppu, Prabhu realizes that he is a man for the country which he is fighting for and that he has no room in his heart for any individual human soul. His country was his life. Prabhu returns home a confused man and tells Yazhini that Karuppu also was in love with her and that he will soon come to marry her. Confusions grow as Prabhu's mother comes to Chennai to meet her future daughter in law. Pandya reveals the truth about Karuppu to everybody and Yazhini realizes that by waiting for Karuppu  she is not giving life its true meaning. The film closes with Yazhini and Prabhu getting together."

In [91]:
# collect unigrams
# case fold, stop word removal, punctuation removal  
def remove_token(token): 
  return token.text.isspace() or token.is_stop or token.is_punct


def tokenize(summ, lemmatize = False):
  doc = nlp(summ)
  if lemmatize: 
    return [token.lemma_ for token in doc if not remove_token(token)]
  else: 
    return [token.text.lower() for token in doc if not remove_token(token)]


df['unigrams'] = df.summary.apply(tokenize)
df['lemmatized'] = df.summary.apply(lambda summ : tokenize(summ, lemmatize = True))


df

,wikipedia id,movie name,genres,summary,unigrams,lemmatized
0,975900,Ghosts of Mars,"[action, adventure, thriller, horror, science ...","Set in the second half of the 22nd century, th...","[set, second, half, 22nd, century, film, depic...","[set, second, half, 22nd, century, film, depic..."
3,18998739,The Sorcerer's Apprentice,"[adventure, family, world cinema, fantasy]","Every hundred years, the evil Morgana returns...","[years, evil, morgana, returns, claim, fingall...","[year, evil, Morgana, return, claim, Fingall, ..."
4,6631279,Little city,"[drama, comedy, romance]","Adam, a San Francisco-based artist who works a...","[adam, san, francisco, based, artist, works, c...","[Adam, San, Francisco, base, artist, work, cab..."
7,11250635,The Mechanical Monsters,"[action, adventure, family, short film, scienc...",The story starts as one of the robots flies i...,"[story, starts, robots, flies, scientist, secr...","[story, start, robot, fly, scientist, secret, ..."
8,77856,Mary Poppins,"[drama, comedy, family, fantasy]",The film opens with Mary Poppins perched in a...,"[film, opens, mary, poppins, perched, cloud, h...","[film, open, Mary, Poppins, perch, cloud, high..."
...,...,...,...,...,...,...
42198,26482675,EÅrefpaÅalÄ±lar,"[drama, comedy]","The film is about two friends, Tayyar , a mafi...","[film, friends, tayyar, mafia, leader, davut, ...","[film, friend, Tayyar, mafia, leader, Davut, n..."
42199,23851782,The Ghost Train,"[comedy, crime, thriller]",{{plot}} The film opens with a Great Western e...,"[plot, film, opens, great, western, express, s...","[plot, film, open, great, western, express, sp..."
42201,34980460,Knuckle,"[drama, documentary]",{{No plot}} This film follows 12 years in the ...,"[plot, film, follows, 12, years, lives, 3, iri...","[plot, film, follow, 12, year, life, 3, irish,..."
42202,913762,The Super Dimension Fortress Macross II: Lover...,"[drama, adventure, short film, science fiction]","The story takes place in the year 2092,The Sup...","[story, takes, place, year, 2092,the, super, d...","[story, take, place, year, 2092,the, Super, Di..."
42203,12476867,Spliced,"[thriller, horror]",The movie is about a teenage girl who loves ho...,"[movie, teenage, girl, loves, horror, movies, ...","[movie, teenage, girl, love, horror, movie, wa..."

In [ ]:
df.loc[42199]['lemmatized']

In [ ]:
# example summary
df.loc[42199]['unigrams']

In [ ]:
# example tokenization
df.loc[42199]['unigrams']

In [93]:
# average number of tokens in summary 
df.unigrams.str.len().mean()

176.49168199938669

In [ ]:
# keep records with at least X tokens 
X = 0
#df = df[df.unigrams.map(len) >= X]